const text = {
  "es": {
    /* Menu */
    "menu-1": {"label": "Inicio", "link": "/"},
    "menu-2": {"label": "Información importante"},
    "menu-2-1": {"label": "Conociendo tu espacio", "link": "/conociendo-tu-espacio"},
    "menu-2-2": {"label": "Cultura y convivencia", "link": "/cultura-y-convivencia"},
    "menu-2-3": {"label": "Documentación", "link": "/documentacion"},
    "menu-2-4": {"label": "Trabajo", "link": "/trabajo"},
    "menu-2-5": {"label": "Salud", "link": "/salud"},
    "menu-2-6": {"label": "Educación", "link": "/educacion"},
    "menu-3": {"label": "Proyecto Hermanitos", "link": "/proyecto-hermanitos"},
    "menu-4": {"label": "Galería", "link": "/galeria"},
    "menu-5": {"label": "Ofrecer empleo", "link": "/ofrecer-empleo"},
    "menu-6": {"label": "Contacto", "link": "/contacto"},
    /* Home */
    "home-title-1": "Conozca el proyecto",
    "home-text-1-1": "Estamos aquí para acoger e integrar a nuestros hermanos venezolanos en Manaos, contribuyendo a su desarrollo y mejora de la calidad de vida. Traemos informaciones, servicios de ciudadanía, noticias y conectamos oportunidades para quien busca trabajar y para quien busca un perfil profesional calificado.",
    "home-text-1-2": "¡Bienvenido a hermanito!",
    "home-title-2-1": "Buscando Oportunidad",
    "home-text-2-1": "Registra tu curriculo",
    "home-title-2-2": "Encontrar Profesionales",
    "home-text-2-2": "Solicitar indicaciones",
    "home-title-3": "Informacion importante",
    "home-grid-link-1": "/conociendo-tu-espacio",
    "home-grid-title-1": "CONOCIENDO TU ESPACIO",
    "home-grid-text-1": "Acabo de llegar a un lugar nuevo? ¡Información para ayudarlo a situarse y adaptarse!",
    "home-grid-link-2": "/cultura-y-convivencia",
    "home-grid-title-2": "CULTURA Y CONVIVENCIA",
    "home-grid-text-2": "Un nuevo país tiene normas y culturas diferentes a las suyas. Comprende aquí un poco sobre Brasil.",
    "home-grid-link-3": "/documentacion",
    "home-grid-title-3": "DOCUMENTACIÓN",
    "home-grid-text-3": "Documentación requerida para vivir en Brasil. Lo que necesitas saber para vivir legalmente.",
    "home-grid-link-4": "/trabajo",
    "home-grid-title-4": "TRABAJO",
    "home-grid-text-4": "El trabajo es esencial para su mantenimiento en Brasil. Consejos sobre cómo buscar oportunidades e ingresar al mercado laboral.",
    "home-grid-link-5": "/salud",
    "home-grid-title-5": "SALUD",
    "home-grid-text-5": "El Sistema de Salud de Brasil es gratuito, pero necesita la tarjeta SUS para acceder a los servicios.",
    "home-grid-link-6": "/educacion",
    "home-grid-title-6": "EDUCACIÓN",
    "home-grid-text-6": "La educación en Brasil es un derecho, incluso para los inmigrantes. Importante saber los lugares y el período de registro.",

    /* Contact */
    "contact-title": "Hable con nosotros",
    "form-title": "Comuníquese con nuestro equipo de atención al público ",
    "form-nombre": "Nombre",
    "form-email": "Email",
    "form-tel": "Telefono",
    "form-asunto": "Asunto",
    "form-mensaje": "Mensaje",
    "form-enviar": "Enviar",
    "cita-1": "Todos somos inmigrantes en el camino de la vida, ninguno de nosotros tiene morada fija en esta tierra",
    "autor-cita-1": "Papa Francisco"
  },
  "pt": {
    /* Menu */
    "menu-1": {"label": "Inicio", "link": "/"},
    "menu-2": {"label": "Informação importante"},
    "menu-2-1": {"label": "Conhecendo seu espaço", "link": "/conhecendo-seu-espaco"},
    "menu-2-2": {"label": "Cultura e convivência", "link": "/cultura-e-convivencia"},
    "menu-2-3": {"label": "Documentação", "link": "/documentacao"},
    "menu-2-4": {"label": "Trabalho", "link": "/trabalho"},
    "menu-2-5": {"label": "Saude", "link": "/saude"},
    "menu-2-6": {"label": "Educação", "link": "/educacao"},
    "menu-3": {"label": "Projeto Hermanitos", "link": "/projeto-hermanitos"},
    "menu-4": {"label": "Galeria", "link": "/galeria"},
    "menu-5": {"label": "Oferecer emprego", "link": "/ofrecer-emprego"},
    "menu-6": {"label": "Contato", "link": "/contato"},
    /* Home */
    "home-title-1": "Conheça o projeto",
    "home-text-1-1": "Estamos aqui para acolher e integrar nossos irmãos venezuelanos em Manaus, contribuindo para o desenvolvimento e melhoria da qualidade de vida. Trazemos informações, serviços de cidadania, notícias e conectamos oportunidades para quem quer trabalhar e para quem procura um perfil profissional qualificado.",
    "home-text-1-2": "Bem-vindo ao hemanito!",
    "home-title-2-1": "Procurando Oportunidade",
    "home-text-2-1": "Registre seu currículo",
    "home-title-2-2": "Encontre Profissionais",
    "home-text-2-2": "Solicitar instruções",
    "home-title-3": "Informação importante",
    "home-grid-link-1": "/conhecendo-seu-espaco",
    "home-grid-title-1": "CONHECENDO O SEU ESPAÇO",
    "home-grid-text-1": "Acabei de chegar em um novo lugar? Informações para ajudá-lo a se posicionar e se adaptar!",
    "home-grid-link-2": "/cultura-e-convivencia",
    "home-grid-title-2": "CULTURA E CONVIVÊNCIA",
    "home-grid-text-2": "Um novo país tem normas e culturas diferentes das suas. Entenda aqui um pouco sobre o Brasil.",
    "home-grid-link-3": "/documentacao",
    "home-grid-title-3": "DOCUMENTAÇÃO",
    "home-grid-text-3": "Documentação necessária para morar no Brasil. O que você precisa saber para viver legalmente.",
    "home-grid-link-4": "/trabalho",
    "home-grid-title-4": "TRABALHO",
    "home-grid-text-4": "O trabalho é essencial para sua manutenção no Brasil. Dicas sobre como procurar oportunidades e entrar no mercado de trabalho.",
    "home-grid-link-5": "/saude",
    "home-grid-title-5": "SAÚDE",
    "home-grid-text-5": "O sistema de saúde brasileiro é gratuito, mas você precisa do cartão SUS para acessar os serviços.",
    "home-grid-link-6": "/educacao",
    "home-grid-title-6": "EDUCAÇÃO",
    "home-grid-text-6": "A educação no Brasil é um direito, mesmo para imigrantes. Importante conhecer os locais e o período de inscrição.",

    /* Contact */
    "contact-title": "Fale conosco",
    "form-title": "Entre em contato com nossa equipe de atendimento ao cliente",
    "form-nombre": "Nome",
    "form-email": "Email",
    "form-tel": "Telefone",
    "form-asunto": "Assunto",
    "form-mensaje": "Mensagem",
    "form-enviar": "Enviar",
    "cita-1": "Somos todos imigrantes no caminho da vida, nenhum de nós tem uma morada fixa nesta terra",
    "autor-cita-1": "Papa Francisco"
  },
  "en": {
    /* Menu */
    "menu-1": {"label": "Home", "link": "/"},
    "menu-2": {"label": "Important information"},
    "menu-2-1": {"label": "Knowing your space", "link": "/knowing-your-space"},
    "menu-2-2": {"label": "Culture and coexistence", "link": "/culture-and-coexistence"},
    "menu-2-3": {"label": "Documentation", "link": "/documentation"},
    "menu-2-4": {"label": "Work", "link": "/work"},
    "menu-2-5": {"label": "Health", "link": "/health"},
    "menu-2-6": {"label": "Education", "link": "/education"},
    "menu-3": {"label": "Project Hermanitos", "link": "/project-hermanitos"},
    "menu-4": {"label": "Gallery", "link": "/gallery"},
    "menu-5": {"label": "Offer employment", "link": "/offer-employment"},
    "menu-6": {"label": "Contact", "link": "/contact"},
    /* Home */
    "home-title-1": "Know the project",
    "home-text-1-1": "We are here to welcome and integrate our Venezuelan brothers in Manaus, contributing to their development and improvement of the quality of life. We bring information, citizenship services, news and connect opportunities for those who are looking to work and for those who are looking for a qualified professional profile.",
    "home-text-1-2": "Welcome little brother!",
    "home-title-2-1": "Looking for Opportunity",
    "home-text-2-1": "Register your resume",
    "home-title-2-2": "Find Professionals",
    "home-text-2-2": "Request directions",
    "home-title-3": "Important information",
    "home-grid-link-1": "/knowing-your-space",
    "home-grid-title-1": "KNOWING YOUR SPACE",
    "home-grid-text-1": "I just got to a new place? Information to help you position yourself and adapt!",
    "home-grid-link-2": "/culture-and-coexistence",
    "home-grid-title-2": "CULTURE AND COEXISTENCE",
    "home-grid-text-2": "A new country has different norms and cultures than its own. Understand a little about Brazil here.",
    "home-grid-link-3": "/documentation",
    "home-grid-title-3": "DOCUMENTATION",
    "home-grid-text-3": "Documentation required to live in Brazil. What you need to know to live legally.",
    "home-grid-link-4": "/work",
    "home-grid-title-4": "WORK",
    "home-grid-text-4": "Work is essential for its maintenance in Brazil. Tips on how to look for opportunities and enter the job market.",
    "home-grid-link-5": "/health",
    "home-grid-title-5": "HEALTH",
    "home-grid-text-5": "The Brazilian Health System is free, but you need the SUS card to access services.",
    "home-grid-link-6": "/education",
    "home-grid-title-6": "EDUCATION",
    "home-grid-text-6": "Education in Brazil is a right, even for immigrants. It is important to know the places and the registration period.",


    /* Contact */
    "contact-title": "Contact us",
    "form-title": "Contact our customer service team",
    "form-nombre": "Name",
    "form-email": "Email",
    "form-tel": "Phone",
    "form-asunto": "Subject",
    "form-mensaje": "Message",
    "form-enviar": "Submit",
    "cita-1": "We are all immigrants on the path of life, none of us has a fixed abode in this land",
    "autor-cita-1": "Papa Francisco"
  }
}

const info = {
  "redes": {
    "facebook": "https://www.facebook.com/EspacoHermanitos/",
    "instagram": "https://www.instagram.com/espaco_hermanitos/",
    "whatsapp": ["https://api.whatsapp.com/send?phone=5592994315431"],
    "linkedin": "https://www.linkedin.com/company/espacohermanitos/about/",
    "tel": ["tel:+5592994315431"]
  }
}

export { text, info };